[package]
name = "masters-thesis-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_rapier2d = { git = "https://github.com/eero-lehtinen/bevy_rapier", branch = "update1", features = [
	"debug-render-2d",
	"serde-serialize",
] }
futures-lite = "2.2.0"
ndarray = "0.15.6"
geo-types = "0.4"
offset-polygon = "0.1.0"
itertools = "0.12.0"
bevy_framepace = "0.14.1"
bevy_pancam = "0.10.0"
